import { defineComponent, ref } from 'vue';
import VRuntimeTemplate from 'vue3-runtime-template';
import type { ExampleModel } from './ExampleModel';
import Editor from '../editor/Editor.vue';
import {
  NeonActionMenu,
  NeonBadge,
  NeonButton,
  NeonCard,
  NeonCardBody,
  NeonCardFooter,
  NeonCardHeader,
  NeonChip,
  NeonColor,
  NeonDialog,
  NeonDrawer,
  NeonDropdown,
  NeonDropdownMenu,
  NeonDropZone,
  NeonExpansionIndicator,
  NeonExpansionPanel,
  NeonFieldGroup,
  NeonFile,
  NeonFilterList,
  NeonFooter,
  NeonGrid,
  NeonGridArea,
  NeonIcon,
  NeonInput,
  NeonInputIndicator,
  NeonLabel,
  NeonLinearProgress,
  NeonLink,
  NeonList,
  NeonLogo,
  NeonMenu,
  NeonModal,
  NeonNote,
  NeonNotificationCounter,
  NeonNumber,
  NeonPage,
  NeonPassword,
  NeonRangeSlider,
  NeonSearch,
  NeonSelect,
  NeonSideNav,
  NeonSkeletonLoader,
  NeonSlider,
  NeonSplashLoader,
  NeonSwitch,
  NeonTab,
  NeonTabs,
  NeonToggle,
  NeonToggleChip,
  NeonTooltip,
  NeonTopNav,
  NeonTreeMenu,
} from '@/neon';
import { NeonIconRegistry } from '../../../common/utils/NeonIconRegistry';

export default defineComponent({
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Example',
  components: {
    Editor,
    NeonActionMenu,
    NeonBadge,
    NeonButton,
    NeonCard,
    NeonCardBody,
    NeonCardFooter,
    NeonCardHeader,
    NeonChip,
    NeonColor,
    NeonDialog,
    NeonDrawer,
    NeonDropdown,
    NeonDropdownMenu,
    NeonDropZone,
    NeonExpansionIndicator,
    NeonExpansionPanel,
    NeonFieldGroup,
    NeonFile,
    NeonFilterList,
    NeonFooter,
    NeonGrid,
    NeonGridArea,
    NeonIcon,
    NeonInput,
    NeonInputIndicator,
    NeonLabel,
    NeonLinearProgress,
    NeonLink,
    NeonList,
    NeonLogo,
    NeonMenu,
    NeonModal,
    NeonNote,
    NeonNotificationCounter,
    NeonNumber,
    NeonPage,
    NeonPassword,
    NeonRangeSlider,
    NeonSearch,
    NeonSelect,
    NeonSideNav,
    NeonSkeletonLoader,
    NeonSlider,
    NeonSplashLoader,
    NeonSwitch,
    NeonTab,
    NeonTabs,
    NeonToggle,
    NeonToggleChip,
    NeonTopNav,
    NeonTooltip,
    NeonTreeMenu,
    VRuntimeTemplate,
  },
  props: {
    example: { type: Object as () => ExampleModel, required: true },
    language: { type: String, default: 'html' },
  },
  setup() {
    const infoIcon = ref(NeonIconRegistry.getIcon('info-circle'));
    return {
      infoIcon,
    };
  },
});
