export const enumList: string[] = [
  'NeonAlertLevel',
  'NeonAlertPlacement',
  'NeonButtonSize',
  'NeonButtonStyle',
  'NeonChipAction',
  'NeonDropdownPlacement',
  'NeonDropdownStyle',
  'NeonFunctionalColor',
  'NeonHorizontalPosition',
  'NeonInputType',
  'NeonLabelSize',
  'NeonMode',
  'NeonOrientation',
  'NeonPlacement',
  'NeonPosition',
  'NeonResponsive',
  'NeonSize',
  'NeonSplashLoaderSize',
  'NeonState',
  'NeonSwitchStyle',
  'NeonToggleStyle',
  'NeonVerticalPosition',
];

export const modelList: string[] = [
  'NeonActionMenuModel',
  'NeonAlertAction',
  'NeonAlertMessage',
  'NeonAvailableSpace',
  'NeonDropdownMenuItem',
  'NeonDropdownPlacementObject',
  'NeonFormattedDate',
  'NeonGridModel',
  'NeonTabModel',
  'NeonToastMessage',
  'NeonToggleModel',
  'NeonTreeMenuModel',
];

export const utilsList: string[] = [
  'NeonAlertService',
  'NeonClipboardService',
  'NeonClosableUtils',
  'NeonDateUtils',
  'NeonDropdownPlacementUtils',
  'NeonEventBus',
  'NeonIconRegistry',
  'NeonModeUtils',
  'NeonPlacementUtils',
  'NeonResponsiveUtils',
  'NeonToastService',
  'RegisterIcons',
];
